"""new fields in user model

Revision ID: 139460394d8b
Revises: 0e091dde8ae4
Create Date: 2018-08-04 07:49:17.993799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139460394d8b'
down_revision = '0e091dde8ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
